version: "3.9"
services:
  db:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - '8432:5432'
    volumes:
      - hr_base-dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  api: &api
    build:
      context: .
      dockerfile: app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

volumes:
  hr_base-dbdata:
