volumes:
  static_data:
    name: hr_base_static_data

services:
  nginx:
    image: nginx:alpine
    environment:
      NGINX_HOST: ${APP_DOMAIN}
      APP_HOST: app
      APP_PORT: 8000

    volumes:
      # local setup
      - ./conf/local/nginx.conf.template:/etc/nginx/templates/default.conf.template
      # static folder
      - static_data:/var/www/static

    ports:
      - 80:80
    healthcheck:
      test: nginx -t
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    image: hr-base
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      # Django settings
      ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      CSRF_COOKIE_DOMAIN: ${APP_DOMAIN}
      DJANGO_HTTP_ENABLED: "yes"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-}
      LOGGING_FORMATTER: verbose
      DATABASE_URL: ${DATABASE_URL}

      # Local settings
      PYTHONPYCACHEPREFIX: "/var/tmp/cache/cpython/"
      DEBUG_TOOLBAR_ENABLED: ${DEBUG_TOOLBAR_ENABLED:-}
      FAIL_FAST: ${FAIL_FAST:-}
    volumes:
      - ./app/:/code/
      # static content
      - static_data:/var/www/static
    depends_on:
      - nginx
