# Generated by Django 5.1 on 2024-08-19 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified on')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(limit_choices_to=models.Q(('role', 'ORG_HR')), on_delete=django.db.models.deletion.PROTECT, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='organisations.organisation')),
                ('updated_by', models.ForeignKey(limit_choices_to=models.Q(('role', 'ORG_HR')), on_delete=django.db.models.deletion.PROTECT, related_name='jobs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified on')),
                ('skill_description', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('org', 'title'), name='unique_organisation_job_title', violation_error_message='Job already created.'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('applicant', 'job'), name='unique_job_applicant', violation_error_message='Application already created.'),
        ),
    ]
