# Generated by Django 5.1 on 2024-08-19 02:20

import django.db.models.deletion
import organisations.generators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified on')),
                ('name', models.TextField(verbose_name='name')),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.TextField(blank=True, null=True)),
                ('staff_access_code', models.CharField(default=organisations.generators.generate_staff_code, max_length=3, unique=True)),
                ('admin', models.OneToOneField(limit_choices_to=models.Q(('role', 'ORG_ADMIN')), on_delete=django.db.models.deletion.PROTECT, related_name='organisation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modified on')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='organisations.organisation')),
                ('user', models.ForeignKey(limit_choices_to=models.Q(('role__in', ['ORG_STAFF', 'ORG_HR'])), on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_organisations_organisation_name', violation_error_code='duplicated', violation_error_message='Record with this name already exists'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('organisation', 'user'), name='unique_organisation_staff', violation_error_message='User is already a staff of the organisation.'),
        ),
    ]
